language: python
matrix:
  include:
  - python: '3.7'
    dist: xenial
  - python: '3.6'
  - python: '3.5'
  - python: '3.4'
    env: EXTRA_PYTEST_ARGS="--pyargs flit_core"
env:
  global:
  - PYTHONPATH=flit_core
install:
- pip install --upgrade pip
- pip install --upgrade pytest
- pip install -r requirements-test.txt
- pip install codecov
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
